# Generated by Django 5.2.5 on 2025-08-12 11:16

import django.core.validators
import django.db.models.deletion
import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('price', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('size', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('image', models.ImageField(blank=True, null=True, upload_to=gallery.models.artwork_upload_to, validators=[gallery.models.validate_image_ext, gallery.models.validate_image_size])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artworks', to='artist.artistprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exhibitions', to='artist.artistprofile')),
                ('artworks', models.ManyToManyField(related_name='exhibitions', to='gallery.artwork')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['artist', 'title'], name='art_by_artist_title'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['artist', '-created_at'], name='art_by_artist_recent'),
        ),
        migrations.AddConstraint(
            model_name='artwork',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_constraint'),
        ),
        migrations.AddConstraint(
            model_name='artwork',
            constraint=models.CheckConstraint(condition=models.Q(('size__gte', 1), ('size__lte', 500)), name='size_constraint'),
        ),
        migrations.AddIndex(
            model_name='exhibition',
            index=models.Index(fields=['artist', '-start_date'], name='exhibitions_by_artist_recent'),
        ),
    ]
