# Generated by Django 5.2.5 on 2025-08-15 10:12

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=gallery.models.exhibition_upload_to, validators=[gallery.models.validate_image_ext, gallery.models.validate_image_size]),
        ),
    ]
