# Generated by Django 5.2.5 on 2025-08-14 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artistapplication',
            name='last_error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='artistapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', '대기'), ('PROCESSING', '처리중'), ('APPROVED', '승인'), ('REJECTED', '반려'), ('ERROR', '오류')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='artistapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'ERROR'])), fields=('applicant',), name='unique_artist_application'),
        ),
    ]
