# Generated by Django 5.2.5 on 2025-08-14 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_artistapplication_last_error_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='artistapplication',
            name='unique_artist_application',
        ),
        migrations.AddConstraint(
            model_name='artistapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'REJECTED'), _negated=True), fields=('applicant',), name='unique_applicant_without_rejected'),
        ),
    ]
